package com.enums;

public enum NotificationType {
	PAYMENT_SUCCESS,
	PAYMENT_FAILED,
	INVOICE_GENERATED,
	LOW_STOCK,
	HIGH_SALES,
	ORDER_PLACED,
	ORDER_SHIPPED,
	ORDER_DELIVERED,
	ORDER_CANCELLED,
	USER_REGISTERED,
	REFUND_INITIATED,
	REFUND_SUCCESS,
	REFUND_FAILED,
	OUT_OF_STOCK
}
